/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lthdt.chuong3.dohoa.frames;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import lthdt.chuong3.coffeelogic.Coffeeshop;
import lthdt.chuong3.coffeelogic.Manager;

/**
 *
 * @author Admin
 */
public class MyCoffee extends javax.swing.JInternalFrame {
    Manager[] managers;
    

    /**
     * Creates new form MyCoffee
     */
    public MyCoffee() throws ParseException {
        initComponents();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        
        Coffeeshop[] a = new Coffeeshop[]{new Coffeeshop ("Kha coffee","2 nguyen hue"),
                                          new Coffeeshop("White garden","4 nguyen hue"),
                                          new Coffeeshop("hoang truc vien","3 nguyen hue")};
      
        managers = new Manager[]{
                             new Manager(a,1000, "Le Thi A", 0, df.parse("12-12-1999")),
                             new Manager(new Coffeeshop[]{
                                 new Coffeeshop("Hoang Hac","12 nguyen hue")
                             },
                                     2000, "Nguyen Van B", 1, df.parse("12-12-2000"))
        };
        for(int i = 0; i< managers.length; i++){
            cbquanly.addItem(managers[i].getHoten());
        }
        
        DefaultTableModel model =(DefaultTableModel)tblcoffeeshop.getModel();
        model.setRowCount(0);
        Coffeeshop[] shops = managers[0].getShops();
        for(int i = 0; i < shops.length; i++){
            model.insertRow(model.getRowCount(), 
                    new Object[]{model.getRowCount() +1,
                        shops[i].getName(),
                        shops[i].getAddress()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbquanly = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcoffeeshop = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("danh sách các quán cafe");

        jLabel1.setText("họ tên người quản lý");

        cbquanly.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbquanlyItemStateChanged(evt);
            }
        });
        cbquanly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbquanlyActionPerformed(evt);
            }
        });

        tblcoffeeshop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Tên quán", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tblcoffeeshop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbquanly, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbquanly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbquanlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbquanlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbquanlyActionPerformed

    private void cbquanlyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbquanlyItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)tblcoffeeshop.getModel();
        model.setRowCount(0);
        int index = cbquanly.getSelectedIndex();
        Coffeeshop[] shops = managers[index].getShops();
        for(int i = 0; i < shops.length; i++){
            model.insertRow(model.getRowCount(), 
                    new Object[]{model.getRowCount() +1,
                        shops[i].getName(),
                        shops[i].getAddress()});
        }
    }//GEN-LAST:event_cbquanlyItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbquanly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcoffeeshop;
    // End of variables declaration//GEN-END:variables
}
