/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lthdt.chuong3.dohoa.frames;

import java.awt.Graphics2D;
import java.util.Random;

/**
 *
 * @author Admin
 */
public class XuatDuLieuFrame extends javax.swing.JInternalFrame {
    int[] a;

    /**
     * Creates new form XuatDuLieuFrame
     */
    public XuatDuLieuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPanel = new javax.swing.JPanel();
        bntve = new javax.swing.JButton();
        bntsapxep = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vẽ dữ liệu mảng 1 chiều");
        setToolTipText("");

        javax.swing.GroupLayout pnPanelLayout = new javax.swing.GroupLayout(pnPanel);
        pnPanel.setLayout(pnPanelLayout);
        pnPanelLayout.setHorizontalGroup(
            pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        pnPanelLayout.setVerticalGroup(
            pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        bntve.setText("Vẽ mảng 1 chiều ra màng hình");
        bntve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntveActionPerformed(evt);
            }
        });

        bntsapxep.setText("Sắp xếp mảng 1 chiều ");
        bntsapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntsapxepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntve)
                    .addComponent(bntsapxep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bntsapxep, bntve, pnPanel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntsapxep)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntveActionPerformed
        // TODO add your handling code here:
        Graphics2D gr = (Graphics2D) pnPanel.getGraphics();
        int maxX = pnPanel.getWidth();
        int maxY = pnPanel.getHeight();
        int step = 5;
        int n = maxX/step;
        int[] a = new int[n];
        Random rnd = new Random();
        for(int i = 0; i< n; i++){
            a[i] = rnd.nextInt(maxY);
        }
        int beginX = 0, beginY = 0;
        for(int i = 0; i< n; i++){
           
            gr.drawRect(beginX,beginY , step , a[i]);
            beginX += step;
        }
    }//GEN-LAST:event_bntveActionPerformed

    private void bntsapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntsapxepActionPerformed
        // TODO add your handling code here:
        Graphics2D gr = (Graphics2D) pnPanel.getGraphics();
        int maxX = pnPanel.getWidth();
        int maxY = pnPanel.getHeight();
        int step = 5;
        int n = maxX/step;
        
        int beginX = 0, beginX2 = 0;
         for(int i = 0; i < n - 1; i++){
          for(int j = i + 1; j < n;j++){
            if(a[i] > a[j]){
                int temp = a[i];
                gr.clearRect(beginX, maxY - a[i], step, a[i]);
                a[i] = a[j];
                gr.drawRect(beginX, maxY - a[i], step, a[i]);
                beginX2 = j*step;
                gr.clearRect(beginX2, maxY - a[j], step, a[j]);
                a[j] = temp;
                gr.drawRect(beginX2, maxY - a[j], step, a[j]);
            }
        }
         beginX += step;  
    }//GEN-LAST:event_bntsapxepActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntsapxep;
    private javax.swing.JButton bntve;
    private javax.swing.JPanel pnPanel;
    // End of variables declaration//GEN-END:variables
}
